//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.09 at 06:51:45 PM BST 
//


package ed.robust.dom.inner;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uploaded" type="{}access_info"/>
 *         &lt;element name="modified" type="{}access_info" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descVersion",
    "dataVersion",
    "uploaded",
    "modified"
})
@XmlRootElement(name = "provenance")
public class Provenance {

    @XmlElement(name = "desc_version", required = true)
    protected int descVersion;
    @XmlElement(name = "data_version", required = true)
    protected int dataVersion;
    @XmlElement(required = true)
    protected AccessInfo uploaded;
    @XmlElement(required = true)
    protected List<AccessInfo> modified;

    /**
     * Gets the value of the uploaded property.
     * 
     * @return
     *     possible object is
     *     {@link AccessInfo }
     *     
     */
    public AccessInfo getUploaded() {
        return uploaded;
    }

    /**
     * Sets the value of the uploaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessInfo }
     *     
     */
    public void setUploaded(AccessInfo value) {
        this.uploaded = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modified property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModified().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessInfo }
     * 
     * 
     */
    public List<AccessInfo> getModified() {
        if (modified == null) {
            modified = new ArrayList<>();
        }
        return this.modified;
    }

    public int getDescVersion() {
        return descVersion;
    }

    public void setDescVersion(int descVersion) {
        if (descVersion <= 0) throw new IllegalArgumentException("Desc version cannot be 0");
        this.descVersion = descVersion;
    }

    public int getDataVersion() {
        return dataVersion;
    }

    public void setDataVersion(int dataVersion) {
        if (dataVersion < 0) throw new IllegalArgumentException("data version cannot be <0");
        this.dataVersion = dataVersion;
    }
    
    public String getVersion() {
        return descVersion+"."+dataVersion;
    }
    
    

}
